version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    #这里的端口是方便管理
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: typecho
      MYSQL_USER: typecho
      MYSQL_PASSWORD: 123456
    deploy:
      placement:
        constraints: [node.role == manager]

  phpfpm:
    image: liwl1iwl/typecho_phpfpm
    depends_on:
      - "mysql"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s

  nginx:
    image: liwl1iwl/typecho_nginx
    depends_on:
      - "mysql"
      - "phpfpm"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s

volumes:
  mysql:
    driver: local
