version: '3.3'

services:
  typecho_mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    #这里的端口是方便管理
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: typecho
      MYSQL_USER: typecho
      MYSQL_PASSWORD: 123456
    deploy:
      placement:
        constraints: [node.role == manager]

  typecho_phpfpm:
    image: liwl1iwl/typecho_phpfpm
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s

  typecho_nginx:
    image: liwl1iwl/typecho_nginx
    depends_on:
      - typecho_mysql
      - typecho_phpfpm
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s

volumes:
  db-data:
    driver: local
